name: Selenium HTML Fetch and Deploy (Every 4 Hours)

# Schedule the action to run every 4 hours
on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Run the Selenium script to generate the HTML
      - name: Run Selenium script
        run: |
          python path_to_your_script.py

      # Rename the generated HTML file for GitHub Pages
      - name: Prepare artifact for deployment
        run: |
          mv git_commit_graph.html index.html  # Rename the HTML file to index.html for GitHub Pages

      # Upload the artifact for deployment in the next job
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          name: pages  # Name of the artifact
          path: index.html  # The file to upload as an artifact

  # Deploy job
  deploy:
    # Add a dependency on the build job
    needs: build

    # Permissions for deploying to GitHub Pages
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Specify the environment as GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Download the artifact produced by the build job
      - name: Download artifact from build
        uses: actions/download-pages-artifact@v1

      # Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Specify the deploy-pages action version
